[alignmentTask]
task_name = 'anatomy'
onto_source_filepath = '/home/jon/explore-bio-ml/logmap-usage/ontologies/mouse.owl'
onto_target_filepath = '/home/jon/explore-bio-ml/logmap-usage/ontologies/human.owl'
generate_extended_mappings_to_ask_oracle = false
logmap_parameters_dirpath = '/home/jon/diff_logmap_llm/logmap-llm/logmap'

# or use `'openrouter'`
interaction_style = 'openai_chat_completions_parse_structured_output'

[oracle]

oracle_dev_prompt_template_name = 'class_equivalence'
oracle_user_prompt_template_name = 'one_level_of_parents_and_synonyms'
local_oracle_predictions_dirpath = '/home/jon/diff_logmap_llm/logmap-usage/local-oracle/'

base_url = 'http://localhost:8000/v1'
openrouter_apikey = 'EMPTY'

enable_thinking = false
interaction_style = 'vllm'

#model_name = 'Qwen/Qwen3-235B-A22B-GPTQ-Int4'
model_name = 'DeepSeek/DeepSeek-R1-Distill-Llama-70B'
#model_name = 'Qwen/Qwen3-32B'

# TODO
#max_workers = 24
#max_completion_tokens

# TODO
#temperature = 0
#top_p = 1

# TODO
#reasoning_effort = 'minimal'

# TODO
#response_format = 

[outputs]
logmapllm_output_dirpath = '/home/jon/diff_logmap_llm/logmap-usage/logmap-llm-outputs/'
logmap_initial_alignment_output_dirpath = '/home/jon/diff_logmap_llm/logmap-usage/logmap-initial-alignment/'
logmap_refined_alignment_output_dirpath = '/home/jon/diff_logmap_llm/logmap-usage/logmap-refined-alignment/'

[pipeline]
align_ontologies = 'align'
build_oracle_prompts = 'build'
consult_oracle = 'consult'
refine_alignment = 'refine'




# 
# LogMap-LLM expert configuration
# 
# Notes:
# - tbd (to be determined)
#

[tableName1]
tbd1 = 'tbd1'

[tableName2]
tbd2 = 'tbd2'

#
# this file will have parameters like:
#
#
# max_completion_tokens
# temperature
# top_p
# reasoning_effort
# response_format 
#
# max_workers
#
# interaction_style_name
# - a new concept being introduced
# - e.g. a way of switching between, say, using the OpenAI chat.completions API and
#   using the OpenAI Responses API, within the same OracleConsultationManager (LLM Server)
#
#

